import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Footer from "../components/footer";
import Whatsapp from "../public/images/whatsapp_white.svg";
import Mail from "../public/images/mail_white.svg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Y&L Vila - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <article className="pw-[100rem] mx-auto pt-36  pb-20 leading-relaxed 2xl:w-full 2xl:px-12 md:px-6 md:pb-10">
          <h1 className="font-sans font-black text-center text-5xl uppercase text-brown tracking-widest leading-tight">
            Contact
          </h1>
          <h2 className="font-sans text-5xl text-brown italic text-center -ml-2 leading-tight">
            Get in touch
          </h2>

          <div className="flex mx-auto w-full justify-center items-center space-x-36 my-28 2xl:justify-between 2xl:space-x-3 md:grid md:grid-cols-2 md:gap-y-10 sm:flex sm:flex-wrap sm:justify-start ">
            <div className=" sm:hidden">
              <Image
                src="/images/linda.png"
                alt="Picture of Coil Slitting"
                width={217}
                height={343}
              />
            </div>
            <div className="hidden  sm:block ">
              <Image
                src="/images/linda_small.png"
                alt="Image of Linda Vogelzang"
                width={136}
                height={213}
              />
            </div>
            <div>
              <div className="mb-12">
                <p className="text-brown font-serif text-xl  ">
                  Linda Vogelzang
                </p>
                <p className="text-gold text-xs sm:text-sm font-serif">Owner</p>
              </div>

              <div>
                <p className="text-brown text-xs ">Spoken languages:</p>
                <p className="text-brown font-normal italic">
                  German, English, French, Dutch
                </p>
              </div>
            </div>

            <div className=" font-bold text-sm md:py-6  md:flex md:flex-wrap md:justify-center md:col-span-2 ">
              <Link href="home">
                <div className="flex items-center border-2 border-brown rounded-full  my-4 md:m-4">
                  <div className="bg-brown p-2 border-2 border-brown inline-block rounded-full ">
                    <Whatsapp />
                  </div>
                  <a className="text-brown px-6 mx-auto sm:text-lg ">
                    +32 4 94 92 45 58
                  </a>
                </div>
              </Link>
              <Link href="home">
                <div className="flex items-center border-2 border-brown rounded-full my-4 md:m-4 ">
                  <div className="bg-brown p-2 border-2 border-brown inline-block rounded-full">
                    <Mail />
                  </div>
                  <a className="text-brown px-6 mx-auto sm:text-lg ">
                    linda@ylvilla.be
                  </a>
                </div>
              </Link>
            </div>
          </div>
        </article>
        <div className="relative">
          <div className="relative">
            <Image
              src="/images/contact.png"
              alt="Picture of Coil Slitting"
              width={1920}
              height={372}
            />
          </div>
          <div className="absolute right-[10%] -top-24 mb-24">
            <Link className="" href="/home">
              <a className="bg-brown text-cream rounded-full w-52 h-52 flex flex-col items-center justify-center	relative font-serif text-center font-bold leading-relaxed md:w-44 md:h-44 md:text-sm">
                Heilige geeststraat 7,
                <span className="font-mono">
                  2000 Antwerpen <br /> Belgium
                </span>
              </a>
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
