import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Contact from "../components/contact";
import Footer from "../components/footer";
import UpperCircle from "../public/images/upper_circle.svg";
import DownCircle from "../public/images/down_circle.svg";
import Cultural from "../public/images/cultural.svg";
import Dining from "../public/images/dining.svg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Y&L Vila - Location</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main>
        <article className="pt-36 w-[100rem] mx-auto 2xl:w-full 2xl:px-12 md:px-6">
          <h1 className="font-sans text-5xl uppercase font-black text-brown tracking-widest sm:text-4xl">
            <span className="font-light">Heilige geeststraat 7,</span> Antwerpen
          </h1>
          <div>
            <div className="border-b-2 border-gold pb-4 my-16 w-[50%] xl:w-[75%] md:w-full md:pb-20 md:mb-6 ">
              <p>
                Villa Y&L, which is located less than 50 meters from
                ‘Vrijdagmarkt’, provides a wonderful location where you can
                enjoy the local market every Friday.
                <br /> <br />
                In the surrounding area you can have many fun activities
                including cycling. Bikes can be rented at the accommodation. Y &
                L Villa is 200 meters from the Our Lady Cathedral and 800 meters
                from the Meir. The Antwerp International Airport is 5km away &
                Brussels international Airport is only 37km away!
              </p>
            </div>
            <div className="relative">
              <div className="relative ">
                <Image
                  src="/images/location.png"
                  alt="Picture of 'de Vrijdagsmarkt'"
                  width={3060}
                  height={984}
                />
              </div>
              <div className="absolute right-[10%] -top-24 mb-24 xl:right-[4%] md:right-[2%]">
                <Link className="" href="/home">
                  <a className="bg-brown text-cream rounded-full w-52 h-52 flex flex-col items-center justify-center	relative font-serif text-center font-bold xl:w-44 xl:h-44">
                    Vrijdagmarkt,
                    <span className="font-mono">Antwerpen</span>
                  </a>
                </Link>
              </div>
            </div>
          </div>
        </article>
        <article className="mt-36 ">
          <div className="w-[100rem] mx-auto mb-16 2xl:w-full 2xl:px-12 md:px-6">
            <h2 className="text-brown text-5xl pb-16  font-black leading-tight flex flex-wrap sm:text-4xl sm:text-center">
              The{" "}
              <span className="relative mx-2 mb-8">
                <UpperCircle className="absolute -mt-6" /> area{" "}
                <DownCircle className="absolute" />
              </span>
              around
              <span className="italic font-light"> Y&L Villa.</span>
            </h2>
            <p>
              Location In the Heart of Historical Centre of Antwerp next to
              shops, restaurants and bars, all what you need.
            </p>
          </div>
          <div className="grid grid-cols-2 gap-12 items-center  mb-20 w-[100rem] mx-auto 2xl:w-full 2xl:px-12 md:px-6 md:flex md:flex-col md:items-start">
            <div className="w-full">
              <div className="flex items-center border-b-2 border-gold pb-4 my-6">
                <Cultural />
                <p className="ml-2">Cultural</p>
              </div>
              <div>
                <ul className="list-disc ml-4 leading-loose">
                  <li>
                    Visit Antwerpen –
                    <span className="text-brown font-serif">
                      www.visitantwerpen.be
                    </span>
                  </li>
                  <li>Museum Plantin-Moretus “next to the house”</li>
                  <li>Cathedral of our Lady,</li>
                  <li>Townhall, Grand Place, Guild Houses</li>
                  <li>Folk Museum</li>
                  <li>Ethnography Museum</li>
                  <li>St Paul’s Church</li>
                  <li>Butcher’s Hall</li>
                  <li>Port Tour</li>
                  <li>St James’s Church</li>
                  <li>Antwerp Zoo</li>
                  <li>Diamond Museum</li>
                  <li>Rubens House</li>
                </ul>
              </div>
            </div>
            <Image
              src="/images/cultural.png"
              alt="Cultural locations in Antwerp"
              width={650}
              height={699}
            />
          </div>
          <div className="bg-darkcream">
            <div className="w-[100rem] mx-auto grid grid-cols-2 gap-12 items-center  py-20  2xl:w-full 2xl:px-12 md:px-6 md:flex md:flex-col-reverse md:items-start md:pt-10">
              <Image
                src="/images/dining.png"
                alt="Images of dining places in Antwerp"
                width={650}
                height={735}
              />
              <div className="w-full">
                <div className="flex items-center border-b-2 border-gold pb-4 my-6">
                  <Dining />
                  <p className="ml-2">Dining</p>
                </div>
                <div>
                  <ul className="list-disc ml-4 leading-loose">
                    <li>
                      Restaurant Invincible –
                      <span className="text-gold font-serif">
                        www.invincible.be
                      </span>
                    </li>
                    <li>
                      Restaurant DIM –
                      <span className="text-gold font-serif">
                        www.dimdining.be
                      </span>
                    </li>
                    <li>Restaurant ’ T Fornuis * Michelin</li>
                    <li>
                      Restaurant Bistrot du Nord –
                      <span className="text-gold font-serif">
                        www.bistrotdunord.be
                      </span>
                    </li>
                    <li>
                      Restaurant ’t Zilte –
                      <span className="text-gold font-serif">
                        www.tzilte.be
                      </span>
                    </li>
                    <li>
                      Restaurant the Jane * Michelin –
                      <span className="text-gold font-serif">
                        www.thejaneantwerp.com
                      </span>
                    </li>
                    <li>
                      Restaurant Het Gebaar –
                      <span className="text-gold font-serif">
                        www.hetgebaar.be
                      </span>
                    </li>
                    <li>
                      Restaurant Roji Sushi –
                      <span className="text-gold font-serif">www.roji.be</span>
                    </li>
                    <li>
                      Restaurant Dock’s cafe –
                      <span className="text-gold font-serif">www.docks.be</span>
                    </li>
                    <li>
                      Restaurant RAS –
                      <span className="text-gold font-serif">
                        www.ras.today
                      </span>
                    </li>
                    <li>
                      Restaurant Pazzo –
                      <span className="text-gold font-serif">www.pazzo.be</span>
                    </li>
                    <li>
                      Restaurant Plateau Royal –
                      <span className="text-gold font-serif">
                        www.plateauroyal.be
                      </span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </article>
        <Contact />
      </main>
      <Footer />
    </div>
  );
}
